In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("sample_k_means_data_3d_3groups.csv")

In [4]:
df.head()

Age  Salary   Debt DO_NOT_USE
0   29   56159  69826          A
1   21   63335  99249          A
2   22   66754  81579          A
3   20   52114  98375          A
4   20   58947  76358          A

In [5]:
cluster_data = df.iloc[:,0:3]

In [6]:
cluster_data.head()

Age  Salary   Debt
0   29   56159  69826
1   21   63335  99249
2   22   66754  81579
3   20   52114  98375
4   20   58947  76358

In [7]:
cluster_data = cluster_data.to_numpy()

In [31]:
def kmeans(data, k, iters = 10):
    # create k random centroids
    centroids = [];
    for i in range(k):
        #centroids.append(np.random.rand(1, data.shape[1]))
        centroids.append(get_random_row(data));
    
    centroids = np.array(centroids)
    print("centroids", centroids)
        
    # create labels for the dataset initially
    labels = np.array([]);        
    labels = np.resize(labels, data.shape[0])
    print(labels)
    
    # assign labels
    assign_labels(data, labels, centroids)
    #print(labels)
    
    index = 0;
    while index < iters:
        
        update_centroids(data, labels, centroids)
        
        assign_labels(data, labels, centroids)
        
        print("centroids", centroids)
        
        index = index + 1
    
    print("final labels", labels)
    labels_df = pd.DataFrame(labels)
    labels_df.to_csv("sample_k_means_data_lable_output.csv", index=False)

def assign_labels(data, labels, centroids):
    # for all rows in data, find min distance to centroids
    for i, row in enumerate(data):
        min_distance = 999999999;
        #print("row", row)
        for j, centroid in enumerate(centroids):            
            #print("centroid", centroid)
            delta = row - centroid
            #print("delta", delta)
            delta_squared = delta * delta
            #print("delta_squared", delta_squared)            
            distance = delta_squared.sum()
            distance = np.sqrt(distance);
            #print("distance", distance)            
            if(distance < min_distance):
                min_distance = distance
                labels[i] = j
            
    return;

def update_centroids(data, labels, centroids):        
    # for all labels get data at row i and keep sum    
    centroids_tmp = np.array([]);
    centroids_tmp = np.resize(centroids_tmp, centroids.shape)    
    
    centroid_counts = np.array([])
    centroid_counts = np.resize(centroid_counts, centroids.shape[0])
    
    
    
    for i, label in enumerate(labels):
        row = data[i]        
        centroids_tmp[label.astype(int)] += row
        centroid_counts[label.astype(int)] += 1
    
    
    
    for i, count in enumerate(centroid_counts):
        centroids[i] = centroids_tmp[i] / (count * 1.0);
        
    
    return

def get_random_row(data):
    index = (np.random.rand() * 1000000) % data.shape[0];   
    index = np.floor(index)
    index = int(index);
    
    return data[index,:];
    

In [33]:
kmeans(cluster_data, 3, 10)

centroids [[    86 146375    473]
 [    23  63544  53978]
 [    41  84130  11125]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
centroids [[    76 143261    606]
 [    27  62562  72442]
 [    45  83685  16180]]
centroids [[    76 143261    606]
 [    24  57246  78636]
 [    45  85062  25127]]
centroids [[    76 143261    606]
 [    24  57246  78636]
 [    45  85062  25127]]
centroids [[    76 143261    606]
 [    24  57246  78636]
 [    45  85062  25127]]
centroids [[    76 143261    606]
 [    24  57246  78636]
 [    45  85062  25127]]
centroids [[    76 143261    606]
 [    24  57246  78636]
 [    45  85062  25127]]
centroids [[    76 143261    606]
 [    24  57246  78636]
 [    45  85062  25127]]
centroids [[    76 143261    606]
 [    24  57246  78636]
 [    45  85062  25127]]
centroids [[    76 143261    606]
 [    24  57246  78636]
 [    45  85062  25127]]
centroids [[    76 143261    606]
 [    24  

In [23]:
get_random_row(cluster_data)

8.0
