In [28]:
import numpy as np

In [29]:
X = np.random.rand(20,2)
ones = np.ones((20,1))
X

array([[0.5257213 , 0.58270498],
       [0.70772753, 0.18775376],
       [0.4287249 , 0.75347804],
       [0.48606436, 0.59407384],
       [0.03974497, 0.99825311],
       [0.47541001, 0.75042248],
       [0.77133093, 0.83733198],
       [0.35747375, 0.85548348],
       [0.21593744, 0.81582131],
       [0.19151091, 0.63205915],
       [0.19230588, 0.51152362],
       [0.0022165 , 0.67281879],
       [0.76867867, 0.07318405],
       [0.05252914, 0.36759637],
       [0.72462135, 0.53074498],
       [0.98770005, 0.4586022 ],
       [0.13276834, 0.15114655],
       [0.62700975, 0.24035356],
       [0.52798799, 0.27403374],
       [0.85744514, 0.69174866]])

In [30]:
Z = np.append(ones, X, axis = 1)
Z

array([[1.        , 0.5257213 , 0.58270498],
       [1.        , 0.70772753, 0.18775376],
       [1.        , 0.4287249 , 0.75347804],
       [1.        , 0.48606436, 0.59407384],
       [1.        , 0.03974497, 0.99825311],
       [1.        , 0.47541001, 0.75042248],
       [1.        , 0.77133093, 0.83733198],
       [1.        , 0.35747375, 0.85548348],
       [1.        , 0.21593744, 0.81582131],
       [1.        , 0.19151091, 0.63205915],
       [1.        , 0.19230588, 0.51152362],
       [1.        , 0.0022165 , 0.67281879],
       [1.        , 0.76867867, 0.07318405],
       [1.        , 0.05252914, 0.36759637],
       [1.        , 0.72462135, 0.53074498],
       [1.        , 0.98770005, 0.4586022 ],
       [1.        , 0.13276834, 0.15114655],
       [1.        , 0.62700975, 0.24035356],
       [1.        , 0.52798799, 0.27403374],
       [1.        , 0.85744514, 0.69174866]])

In [20]:
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])